using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Avalonia.Plugin.CodeGenerator
{
    /// <summary>
    /// 插件代码生成器 - 自动生成 IPlugin 实现类
    /// </summary>
    [Generator]
    public class PluginGenerator : IIncrementalGenerator
    {
        // 诊断描述符常量
        private static class DiagnosticDescriptors
        {
            public static readonly DiagnosticDescriptor FoundClasses = new DiagnosticDescriptor(
                "PG001", "Plugin Generator", "Found {0} classes with MenuAttribute", "Plugin Generator",
                DiagnosticSeverity.Info, true);

            public static readonly DiagnosticDescriptor ProjectNamespace = new DiagnosticDescriptor(
                "PG002", "Plugin Generator", "Project namespace: {0}", "Plugin Generator",
                DiagnosticSeverity.Info, true);

            public static readonly DiagnosticDescriptor GeneratedFile = new DiagnosticDescriptor(
                "PG003", "Plugin Generator", "Generated {0}", "Plugin Generator",
                DiagnosticSeverity.Info, true);

            public static readonly DiagnosticDescriptor NoClassesFound = new DiagnosticDescriptor(
                "PG004", "Plugin Generator", "No classes with MenuAttribute found", "Plugin Generator",
                DiagnosticSeverity.Info, true);

            public static readonly DiagnosticDescriptor NoNamespaceFound = new DiagnosticDescriptor(
                "PG005", "Plugin Generator", "No project namespace found", "Plugin Generator",
                DiagnosticSeverity.Info, true);
        }

        // 常量定义
        private const string MenuAttributeFullName = "Avalonia.Plugin.Shared.Attributes.MenuAttribute";
        private const string GeneratedFileName = "GeneratedPlugin.g.cs";
        private const string GeneratedClassName = "GeneratedPlugin";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
#if DEBUG
            AttachDebugger();
#endif

            // 注册初始化输出
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
                "PluginGenerator.g.cs",
                SourceText.From("// Auto-generated by PluginGenerator", Encoding.UTF8)));

            // 创建语法提供器 - 筛选带 MenuAttribute 的类声明
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: IsCandidateClass,
                    transform: GetClassWithMenuAttribute)
                .Where(item => item != null)
                .Collect();

            // 组合编译信息和类声明
            var compilationAndClasses = context.CompilationProvider
                .Combine(classDeclarations);

            // 注册源代码输出
            context.RegisterSourceOutput(compilationAndClasses, (spc, src) => GeneratePluginCode(spc, src.Left, src.Right));
        }

        /// <summary>
        /// 调试模式下附加调试器
        /// </summary>
        private static void AttachDebugger()
        {
            if (!System.Diagnostics.Debugger.IsAttached)
            {
                System.Diagnostics.Debugger.Launch();
            }
        }

        /// <summary>
        /// 判断是否为候选类（有特性的类声明）
        /// </summary>
        private static bool IsCandidateClass(SyntaxNode node, CancellationToken _)
        {
            return node is ClassDeclarationSyntax classDecl && classDecl.AttributeLists.Count > 0;
        }

        /// <summary>
        /// 获取带有 MenuAttribute 的类信息
        /// </summary>
        private static ClassMenuInfo GetClassWithMenuAttribute(GeneratorSyntaxContext context, CancellationToken _)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;

            // 快速语法检查 - 过滤包含 "Menu" 的特性
            if (!HasMenuAttributeSyntax(classDecl))
                return null;

            // 语义模型确认
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);
            if (symbol == null)
                return null;

            var menuAttribute = symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass != null && a.AttributeClass.ToDisplayString() == MenuAttributeFullName);

            if (menuAttribute == null)
                return null;

            return ExtractClassMenuInfo(classDecl, symbol, menuAttribute);
        }

        /// <summary>
        /// 语法层面检查是否有 Menu 相关特性
        /// </summary>
        private static bool HasMenuAttributeSyntax(ClassDeclarationSyntax classDecl)
        {
            return classDecl.AttributeLists
                .SelectMany(al => al.Attributes)
                .Any(a => a.Name.ToString().Contains("Menu"));
        }

        /// <summary>
        /// 提取类的菜单信息
        /// </summary>
        private static ClassMenuInfo ExtractClassMenuInfo(
            ClassDeclarationSyntax classDecl,
            INamedTypeSymbol symbol,
            AttributeData menuAttribute)
        {
            var info = new ClassMenuInfo
            {
                ClassName = classDecl.Identifier.Text,
                Namespace = GetNamespace(classDecl)
            };

            // 提取构造函数参数
            if (menuAttribute.ConstructorArguments.Length >= 2)
            {
                info.Header = menuAttribute.ConstructorArguments[0].Value?.ToString();
                info.Key = menuAttribute.ConstructorArguments[1].Value?.ToString();
            }

            // 提取命名参数
            foreach (var namedArg in menuAttribute.NamedArguments)
            {
                switch (namedArg.Key)
                {
                    case "ParentKey":
                        info.ParentKey = namedArg.Value.Value?.ToString();
                        break;
                    case "Status":
                        info.Status = namedArg.Value.Value?.ToString();
                        break;
                    case "Order":
                        if (namedArg.Value.Value is int order)
                            info.Order = order;
                        break;
                }
            }

            return info;
        }

        /// <summary>
        /// 获取类的命名空间
        /// </summary>
        private static string GetNamespace(ClassDeclarationSyntax classDecl)
        {
            var namespaceDecl = classDecl.Ancestors()
                .OfType<NamespaceDeclarationSyntax>()
                .FirstOrDefault();

            if (namespaceDecl != null)
                return namespaceDecl.Name.ToString();

            // 支持文件范围的命名空间 (C# 10+)
            var fileScopedNamespace = classDecl.SyntaxTree.GetRoot()
                .DescendantNodes()
                .OfType<FileScopedNamespaceDeclarationSyntax>()
                .FirstOrDefault();

            return fileScopedNamespace?.Name.ToString();
        }

        /// <summary>
        /// 生成插件代码
        /// </summary>
        private static void GeneratePluginCode(
            SourceProductionContext context,
            Compilation compilation,
            ImmutableArray<ClassMenuInfo> classes)
        {
            var validClasses = classes.Where(c => c != null).ToList();

            // 报告发现的类数量
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.FoundClasses, Location.None, validClasses.Count));

            if (validClasses.Count == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.NoClassesFound, Location.None));
                return;
            }

            // 确定项目命名空间
            var projectNamespace = validClasses.First().Namespace;
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.ProjectNamespace, Location.None, projectNamespace ?? "(null)"));

            if (string.IsNullOrEmpty(projectNamespace))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.NoNamespaceFound, Location.None));
                return;
            }

            // 生成代码
            var code = GeneratePluginClassCode(projectNamespace, validClasses);
            context.AddSource(GeneratedFileName, SourceText.From(code, Encoding.UTF8));

            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.GeneratedFile, Location.None, GeneratedFileName));
        }

        /// <summary>
        /// 生成插件类代码
        /// </summary>
        private static string GeneratePluginClassCode(string projectNamespace, List<ClassMenuInfo> classes)
        {
            var sb = new StringBuilder();

            // 文件头
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by Avalonia.Plugin.CodeGenerator");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Avalonia.Plugin.Shared;");
            sb.AppendLine("using Avalonia.Plugin.Shared.ViewModels;");
            sb.AppendLine();
            sb.AppendLine($"namespace {projectNamespace};");
            sb.AppendLine();

            // 类声明
            sb.AppendLine($"public class {GeneratedClassName} : IPlugin, IResourceAssemblyIdentifier");
            sb.AppendLine("{");

            // IResourceAssemblyIdentifier 接口实现
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine($"    public string PluginId => \"{projectNamespace}\";");
            sb.AppendLine();
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public string Author => \"Generated\");");
            sb.AppendLine();
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public string Description => \"Auto-generated plugin\");");
            sb.AppendLine();
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public System.Collections.Generic.IEnumerable<string> Dependencies => System.Array.Empty<string>();");
            sb.AppendLine();

            // IPlugin 接口实现
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public string Name => \"Generated Plugin\");");
            sb.AppendLine();
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public string Version => \"1.0.0\");");
            sb.AppendLine();

            // Initialize 方法
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public void Initialize()");
            sb.AppendLine("    {");
            sb.AppendLine("        // 插件初始化逻辑");
            sb.AppendLine("    }");
            sb.AppendLine();

            // GetNavigationItems 方法
            GenerateNavigationItemsMethod(sb, classes);
            sb.AppendLine();

            // GetMenuItems 方法
            GenerateMenuItemsMethod(sb, classes);
            sb.AppendLine();

            // GetAssembly 方法
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public System.Reflection.Assembly GetAssembly()");
            sb.AppendLine("    {");
            sb.AppendLine("        return GetType().Assembly;");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 生成 GetNavigationItems 方法
        /// </summary>
        private static void GenerateNavigationItemsMethod(StringBuilder sb, List<ClassMenuInfo> classes)
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public Dictionary<string, ViewModelFactory> GetNavigationItems()");
            sb.AppendLine("    {");
            sb.AppendLine("        return new Dictionary<string, ViewModelFactory>");
            sb.AppendLine("        {");

            foreach (var info in classes)
            {
                if (!string.IsNullOrEmpty(info.Key))
                {
                    sb.AppendLine($"            {{ \"{info.Key}\", () => new {info.ClassName}() }},");
                }
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成 GetMenuItems 方法
        /// </summary>
        private static void GenerateMenuItemsMethod(StringBuilder sb, List<ClassMenuInfo> classes)
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public IEnumerable<(string? ParentKey, MenuItemViewModel MenuItem)> GetMenuItems()");
            sb.AppendLine("    {");

            foreach (var info in classes)
            {
                if (string.IsNullOrEmpty(info.Header) || string.IsNullOrEmpty(info.Key))
                    continue;

                var parentKeyValue = string.IsNullOrEmpty(info.ParentKey) ? "null" : $"\"{info.ParentKey}\"";
                sb.AppendLine($"        yield return ({parentKeyValue}, new MenuItemViewModel");
                sb.AppendLine("        {");
                sb.AppendLine($"            MenuHeader = \"{EscapeString(info.Header)}\",");
                sb.AppendLine($"            Key = \"{info.Key}\",");

                if (!string.IsNullOrEmpty(info.Status))
                {
                    sb.AppendLine($"            Status = \"{info.Status}\",");
                }

                if (info.Order != 0)
                {
                    sb.AppendLine($"            Order = {info.Order}");
                }
                else
                {
                    // 移除最后一个逗号
                    var lines = sb.ToString().Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
                    var lastLine = lines.Length > 0 ? lines[lines.Length - 1] : null;
                    if (lastLine != null && lastLine.EndsWith(","))
                    {
                        sb.Length = sb.Length - 1;
                        sb.AppendLine();
                    }
                }

                sb.AppendLine("        });");
            }

            sb.AppendLine("    }");
        }

        /// <summary>
        /// 转义字符串中的特殊字符
        /// </summary>
        private static string EscapeString(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t");
        }

        /// <summary>
        /// 类菜单信息
        /// </summary>
        private class ClassMenuInfo
        {
            public string ClassName { get; set; } = string.Empty;
            public string Namespace { get; set; } = string.Empty;
            public string Header { get; set; } = string.Empty;
            public string Key { get; set; } = string.Empty;
            public string ParentKey { get; set; } = string.Empty;
            public string Status { get; set; } = string.Empty;
            public int Order { get; set; }
        }
    }
}
