using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace Avalonia.Plugin.CodeGenerator;

[Generator]
public class PluginGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 注册源生成器
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "PluginGenerator.g.cs",
            SourceText.From("// Auto-generated by PluginGenerator", Encoding.UTF8)));

        // 筛选出带有MenuAttribute特性的类
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax,
                transform: (ctx, _) => GetClassWithMenuAttribute(ctx))
            .Where(t => t != null);

        // 收集所有带有MenuAttribute特性的类
        var compilationAndClasses = context.CompilationProvider
            .Combine(classDeclarations.Collect());

        // 生成代码
        context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
            Execute(source.Left, source.Right, spc));
    }

    private ClassDeclarationSyntax? GetClassWithMenuAttribute(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        // 检查类是否带有MenuAttribute特性
        foreach (var attributeList in classDecl.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                // 尝试获取特性的符号信息
                var attributeSymbol = semanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
                if (attributeSymbol != null)
                {
                    var attributeType = attributeSymbol.ContainingType;
                    if (attributeType.Name == "MenuAttribute")
                    {
                        return classDecl;
                    }
                }
            }
        }

        return null;
    }

    private void Execute(Compilation compilation, IEnumerable<ClassDeclarationSyntax> classes, SourceProductionContext context)
    {
        // 输出调试信息
        context.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor("PG001", "Plugin Generator", $"Found {classes.Count()} classes with MenuAttribute", "Plugin Generator", DiagnosticSeverity.Info, true),
            Location.None));

        if (!classes.Any())
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("PG004", "Plugin Generator", "No classes with MenuAttribute found", "Plugin Generator", DiagnosticSeverity.Info, true),
                Location.None));
            return;
        }

        // 获取当前项目的命名空间
        var projectNamespace = GetProjectNamespace(compilation);
        context.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor("PG002", "Plugin Generator", $"Project namespace: {projectNamespace}", "Plugin Generator", DiagnosticSeverity.Info, true),
            Location.None));

        if (string.IsNullOrEmpty(projectNamespace))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("PG005", "Plugin Generator", "No project namespace found", "Plugin Generator", DiagnosticSeverity.Info, true),
                Location.None));
            return;
        }

        // 生成插件实现类
        var pluginClassCode = GeneratePluginClassCode(projectNamespace, classes, compilation);
        context.AddSource("GeneratedPlugin.g.cs", SourceText.From(pluginClassCode, Encoding.UTF8));
        context.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor("PG003", "Plugin Generator", "Generated GeneratedPlugin.g.cs", "Plugin Generator", DiagnosticSeverity.Info, true),
            Location.None));
    }

    private string GetProjectNamespace(Compilation compilation)
    {
        // 获取第一个类的命名空间作为项目的命名空间
        var firstClass = compilation.SyntaxTrees
            .SelectMany(tree => tree.GetRoot().DescendantNodes())
            .OfType<ClassDeclarationSyntax>()
            .FirstOrDefault();

        if (firstClass != null)
        {
            var namespaceDecl = firstClass.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
            if (namespaceDecl != null)
            {
                return namespaceDecl.Name.ToString();
            }
        }

        return string.Empty;
    }

    private string GeneratePluginClassCode(string projectNamespace, IEnumerable<ClassDeclarationSyntax> classes, Compilation compilation)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by PluginGenerator");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Avalonia.Plugin.Shared;");
        sb.AppendLine("using Avalonia.Plugin.Shared.ViewModels;");
        sb.AppendLine();
        sb.AppendLine($"namespace {projectNamespace};");
        sb.AppendLine();
        sb.AppendLine("public class GeneratedPlugin : IPlugin");
        sb.AppendLine("{");
        sb.AppendLine("    public string Name => \"Generated Plugin\";\n");
        sb.AppendLine("    public string Version => \"1.0.0\";\n");
        sb.AppendLine("    public void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        // 插件初始化逻辑");
        sb.AppendLine("    }\n");
        sb.AppendLine("    public Dictionary<string, ViewModelFactory> GetNavigationItems()");
        sb.AppendLine("    {");
        sb.AppendLine("        var navigationItems = new Dictionary<string, ViewModelFactory>");
        sb.AppendLine("        {");

        // 生成导航项
        foreach (var classDecl in classes)
        {
            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as ITypeSymbol;
            if (classSymbol == null)
                continue;

            // 获取MenuAttribute特性
            var menuAttribute = classSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "MenuAttribute" &&
                    a.AttributeClass.ContainingNamespace.Name == "Attributes" &&
                    a.AttributeClass.ContainingNamespace.ContainingNamespace.Name == "Avalonia.Plugin.Shared");

            if (menuAttribute == null)
                continue;

            // 解析特性参数
            var key = menuAttribute.ConstructorArguments[1].Value as string;
            if (key != null)
            {
                var className = classSymbol.Name;
                sb.AppendLine($"            {{ \"{key}\", () => new {className}() }},");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("        return navigationItems;");
        sb.AppendLine("    }\n");
        sb.AppendLine("    public IEnumerable<(string? ParentKey, MenuItemViewModel MenuItem)> GetMenuItems()");
        sb.AppendLine("    {");
        sb.AppendLine("        var menuItems = new List<(string? ParentKey, MenuItemViewModel MenuItem)>();");
        sb.AppendLine();

        // 生成菜单项
        foreach (var classDecl in classes)
        {
            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as ITypeSymbol;
            if (classSymbol == null)
                continue;

            // 获取MenuAttribute特性
            var menuAttribute = classSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "MenuAttribute" &&
                    a.AttributeClass.ContainingNamespace.Name == "Attributes" &&
                    a.AttributeClass.ContainingNamespace.ContainingNamespace.Name == "Avalonia.Plugin.Shared");

            if (menuAttribute == null)
                continue;

            // 解析特性参数
            var header = menuAttribute.ConstructorArguments[0].Value as string;
            var key = menuAttribute.ConstructorArguments[1].Value as string;
            var parentKey = menuAttribute.NamedArguments.FirstOrDefault(a => a.Key == "ParentKey").Value.Value as string;
            var status = menuAttribute.NamedArguments.FirstOrDefault(a => a.Key == "Status").Value.Value as string;
            var order = menuAttribute.NamedArguments.FirstOrDefault(a => a.Key == "Order").Value.Value as int? ?? 0;

            if (header != null && key != null)
            {
                sb.AppendLine("        var menuItem = new MenuItemViewModel");
                sb.AppendLine("        {");
                sb.AppendLine($"            MenuHeader = \"{header}\",");
                sb.AppendLine($"            Key = \"{key}\",");
                if (!string.IsNullOrEmpty(status))
                {
                    sb.AppendLine($"            Status = \"{status}\",");
                }
                sb.AppendLine($"            Order = {order}");
                sb.AppendLine("        };");
                sb.AppendLine("        menuItems.Add((" + (parentKey != null ? $"\"{parentKey}\"" : "null") + ", menuItem));");
                sb.AppendLine();
            }
        }

        sb.AppendLine("        return menuItems;");
        sb.AppendLine("    }\n");
        sb.AppendLine("    public System.Reflection.Assembly GetAssembly()");
        sb.AppendLine("    {");
        sb.AppendLine("        return GetType().Assembly;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}